-- Supabase 数据库设置脚本
-- 在 Supabase SQL 编辑器中执行此脚本

-- 1. 创建 destinations 表
CREATE TABLE IF NOT EXISTS destinations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  location TEXT NOT NULL,
  description TEXT,
  image TEXT,
  price TEXT,
  duration TEXT,
  tags TEXT[] DEFAULT '{}',
  rating DECIMAL(2,1) DEFAULT 0,
  reviews INTEGER DEFAULT 0,
  recommended BOOLEAN DEFAULT false,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. 启用行级安全策略 (RLS)
ALTER TABLE destinations ENABLE ROW LEVEL SECURITY;

-- 3. 创建策略 - 允许所有人读取数据
CREATE POLICY "Allow public read access" ON destinations
  FOR SELECT
  USING (true);

-- 4. 创建策略 - 允许管理员插入数据
CREATE POLICY "Allow admin insert access" ON destinations
  FOR INSERT
  WITH CHECK (true);

-- 5. 创建策略 - 允许管理员更新数据
CREATE POLICY "Allow admin update access" ON destinations
  FOR UPDATE
  USING (true);

-- 6. 创建索引以优化查询性能
CREATE INDEX IF NOT EXISTS idx_destinations_name ON destinations(name);
CREATE INDEX IF NOT EXISTS idx_destinations_location ON destinations(location);
CREATE INDEX IF NOT EXISTS idx_destinations_recommended ON destinations(recommended);

-- 7. 插入示例数据
INSERT INTO destinations (name, location, description, image, price, duration, tags, rating, reviews, recommended) VALUES
(
  '巴厘岛',
  '印度尼西亚',
  '体验热带天堂的魅力，享受私人海滩和豪华度假村，探索古老寺庙和稻田美景',
  'https://images.unsplash.com/photo-1714412192114-61dca8f15f68?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx0cm9waWNhbCUyMGJlYWNoJTIwcGFyYWRpc2V8ZW58MXx8fHwxNzY4MDA3NDk2fDA&ixlib=rb-4.1.0&q=80&w=1080',
  '¥4,500',
  '7天6晚',
  ARRAY['海滩', '度假', '文化'],
  4.8,
  1240,
  true
),
(
  '巴黎',
  '法国',
  '漫步在浪漫之都的街头，参观埃菲尔铁塔、卢浮宫，品尝正宗法式美食',
  'https://images.unsplash.com/photo-1431274172761-fca41d930114?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxwYXJpcyUyMGVpZmZlbCUyMHRvd2VyfGVufDF8fHx8MTc2Nzk4MzIyNnww&ixlib=rb-4.1.0&q=80&w=1080',
  '¥8,800',
  '10天9晚',
  ARRAY['城市', '文化', '美食'],
  4.9,
  2156,
  true
),
(
  '东京',
  '日本',
  '探索现代科技与传统文化完美融合的国际大都市，体验独特的日本风情',
  'https://images.unsplash.com/photo-1583915223588-7d88ebf23414?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx0b2t5byUyMGNpdHklMjBuaWdodHxlbnwxfHx8fDE3NjgwNDg2Mzl8MA&ixlib=rb-4.1.0&q=80&w=1080',
  '¥6,200',
  '6天5晚',
  ARRAY['城市', '购物', '美食'],
  4.7,
  1890,
  false
),
(
  '瑞士阿尔卑斯',
  '瑞士',
  '在壮观的雪山景色中度假，体验滑雪、徒步等户外活动，享受纯净自然',
  'https://images.unsplash.com/photo-1597434429739-2574d7e06807?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtb3VudGFpbiUyMGxhbmRzY2FwZSUyMG5hdHVyZXxlbnwxfHx8fDE3Njc5ODgxMTB8MA&ixlib=rb-4.1.0&q=80&w=1080',
  '¥12,000',
  '8天7晚',
  ARRAY['自然', '冒险', '滑雪'],
  4.9,
  987,
  false
),
(
  '圣托里尼',
  '希腊',
  '欣赏爱琴海的绝美日落，漫步白色小镇，享受浪漫的地中海风情',
  'https://images.unsplash.com/photo-1664112732671-877dc0030ba7?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxzYW50b3JpbmklMjBncmVlY2UlMjBpc2xhbmR8ZW58MXx8fHwxNzY4MDQ4NjQwfDA&ixlib=rb-4.1.0&q=80&w=1080',
  '¥7,600',
  '7天6晚',
  ARRAY['海岛', '浪漫', '摄影'],
  4.8,
  1567,
  true
),
(
  '纽约',
  '美国',
  '体验不夜城的繁华魅力，参观自由女神像、时代广场、中央公园等地标',
  'https://images.unsplash.com/photo-1570304816841-906a17d7b067?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxuZXclMjB5b3JrJTIwc2t5bGluZXxlbnwxfHx8fDE3Njc5Mzk0NTl8MA&ixlib=rb-4.1.0&q=80&w=1080',
  '¥9,500',
  '9天8晚',
  ARRAY['城市', '购物', '艺术'],
  4.6,
  2341,
  false
);

-- 8. 验证数据
SELECT * FROM destinations;
